const classLabPrompts = [
  {
    type: "numberentry",
    fieldTitle: "Ammonia - N",
    value: "ammonia",
    id: "cl_ammonia",
    min: "0",
    max: "10",
    label: "ppm(mg/L)",
    required: true,
  },
  {
    type: "numberentry",
    fieldTitle: "Calcium hardness",
    value: "calcium",
    id: "cl_calcium",
    min: "0",
    max: "1000",
    label: "ppm(mg/L)",
    required: true,
  },
  {
    type: "numberentry",
    id: "cl_chloride",
    fieldTitle: "Chloride",
    value: "chloride",
    min: "0",
    max: "400",
    label: "ppm(mg/L)",
    required: true,
  },
  {
    type: "dropdownentry",
    fieldTitle: "Bacteria (Colilert)",
    id: "cl_bacteria",
    options: [
      "Clear",
      "Yellow with flourescent rim",
      "Yellow without flourescent rim",
    ],
    value: "bacteria",
    required: true,
  },
  {
    type: "numberentry",
    fieldTitle: "Copper",
    value: "copper",
    id: "cl_copper",
    min: "0",
    max: "400",
    label: "ppm(mg/L)",
    required: true,
  },
  {
    type: "numberentry",
    fieldTitle: "Iron",
    id: "cl_iron",
    value: "iron",
    min: "0",
    max: "400",
    label: "ppm(mg/L)",
    required: true,
  },
  {
    type: "numberentry",
    fieldTitle: "Manganese",
    id: "cl_manganese",
    value: "manganese",
    min: "0",
    max: "400",
    label: "ppm(mg/L)",
    required: true,
  },
  {
    type: "numberentry",
    fieldTitle: "Nitrate - N",
    id: "cl_nitrate",
    value: "nitrate",
    min: "0",
    max: "200",
    label: "ppm(mg/L)",
    required: true,
  },
  {
    type: "shorttextentry",
    fieldTitle: "Data Collector's Name:",
    value: "name",
    id: "cl_name",
    required: true,
  },
  {
    type: "longtextentry",
    fieldTitle: "Observations:",
    id: "cl_observation",
    value: "observation",
    required: false,
  },
];

export default classLabPrompts;
