const classLabPrompts = [
    {
        type: "numberentry",
        fieldTitle: "Ammonia - N",
        value: "ammonia",
        id: "ammonia",
        min: "0",
        max: "10",
        label: "ppm(mg/L)",
        required: true
    },
    {
        type: "numberentry",
        fieldTitle: "Calcium hardness",
        value: "calcium",
        id: "calcium",
        min: "0",
        max: "1000",
        label: "ppm(mg/L)",
        required: true,
    },
    {
        type: "numberentry",
        id: "chloride",
        fieldTitle: "Chloride",
        value: "chloride",
        min: "0",
        max: "400",
        label: "ppm(mg/L)",
        required: true,
    },
    {
        type: "dropdownentry",
        fieldTitle: "Bacteria (Colilert)",
        id: "bacteria",
        options: ["Clear", "Yellow with flourescent rim", "Yellow without flourescent rim"],
        value: "bacteria",
        required: true,
    },
    {
        type: "numberentry",
        fieldTitle: "Copper",
        value: "copper",
        id: "copper",
        min: "0",
        max: "400",
        label: "ppm(mg/L)",
        required: true,
    },
    {
        type: "numberentry",
        fieldTitle: "Iron",
        id: "iron",
        value: "iron",
        min: "0",
        max: "400",
        label: "ppm(mg/L)",
        required: true,
    },
    {
        type: "numberentry",
        fieldTitle: "Manganese",
        id: "manganese",
        value: "manganese",
        min: "0",
        max: "400",
        label: "ppm(mg/L)",
        required: true,
    },
    {
        type: "numberentry",
        fieldTitle: "Nitrate - N",
        id: "nitrate",
        value: "nitrate",
        min: "0",
        max: "200",
        label: "ppm(mg/L)",
        required: true,
    },
    {
        type: "shorttextentry",
        fieldTitle: "Data Collector's Name:",
        value: "name",
        id: "name",
        required: true,
    },
    {
        type: "longtextentry",
        fieldTitle: "Observations:",
        id: "observation",
        value: "observation",
        required: false,
    },
];

export default classLabPrompts;