const csvKey = {
  sch_name: "School Name",
  wi_wellcode: "Well Code",
  wi_wellname: "Well Name",
  wi_well_user: "Name of resident well user",
  wi_address: "Address",
  wi_city: "City",
  wi_state: "State",
  wi_zipcode: "Zipcode",
  county_name: "County",
  nrd_name: "Natural Resource District",
  wi_phone_well_user: "Phone number (of well user)",
  wi_email_well_user: "Email (of well user)",
  wi_well_owner: "Well owner (if different from resident)",
  wi_installyear: "Well construction completion year",
  wi_smelltaste: "Complaints of smell or taste",
  wi_smelltaste_description: "Description of smell or taste",
  wi_welldry: "Does the well go dry",
  wi_welldry_description: "Description of well going dry",
  wi_maintenance5yr: "Any maintenance done to well in last 5 years",
  wi_landuse5yr:
    "Any major land use/development changes around well in last 5 years",
  wi_numberwelluser: "Number of well users",
  wi_pestmanure:
    "Have manure/fertilizer/pesticides been applied near well in last 5 years",
  wi_estlatitude: "Well Estimated Latitude",
  wi_estlongitude: "Well Estimated Longitude",
  wi_boreholediameter: "Well Bore hole diameter (inches)",
  wi_totaldepth: "Total Depth of Well (feet)",
  wi_waterleveldepth: "Water level (feet)",
  wi_aquifertype: "Aquifer type",
  wi_aquiferclass: "Aquifer class",
  wi_welltype: "Well Type (Construction Method)",
  wi_wellcasematerial: "Well Casing Material",
  wi_dnr_well_id: "DNR Well ID",
  wi_registration_number: "Well Registration Number",
  wi_datacollector: "Well Form Data Collector",
  wi_observation: "Well Observations",
  wi_dateentered: "Well Form Date Entered",
  fa_latitude: "Field Latitude",
  fa_longitude: "Field Longitude",
  fa_weather: "Field Weather Conditions",
  fa_wellcovercondition: "Well Cover Condition",
  fa_wellcoverdescription: "Well Cover Description",
  fa_surfacerunoff: "Evidence of surface run-off at entry of well",
  fa_pooling: "Evidence of pooling or puddles within 12 ft of well",
  fa_groundwatertemp: "Groundwater temp",
  fa_ph: "ph [0-14]",
  fa_conductivity: "Conductivity [100-2000 uS/cm]",
  fa_topography: "Topography of well location",
  fa_datacollector: "Field Form Data Collector",
  fa_observation: "Field Observations",
  fa_datecollected: "Field Date Collected",
  cl_ammonia: "Ammonia [0-10 ppm(mg/L)]",
  cl_calciumhardness: "Calcium Hardness [50-500 ppm(mg/L)]",
  cl_chloride: "Chloride [0-400 ppm(mg/L)]",
  cl_bacteria: "Bacteria (Coilert)",
  cl_copper: "Copper [0-10 ppm(mg/L)]",
  cl_iron: "Iron [0-10 ppm(mg/L)]",
  cl_manganese: "Mangenese [0-50 ppm(mg/L)]",
  cl_nitrate: "Nitrate [0-45 ppm(mg/L)]",
  cl_observation: "Class Lab Observations",
  cl_nitrite: "Nitrate [0-45 ppm(mg/L)]",
  cl_pest_atrazine: "Pesticide/Atrazine (ug/L)",
  cl_datacollector: "Class Lab Data Collector",
  cl_datecollected: "Class Lab Date Entered",
  wsl_samplecode: "Water Science Lab Code",
  wsl_ph: "WSL pH [1-14 (unitless)]",
  wsl_conductivity: "WSL Conductivity (uS/cm)",
  wsl_calciumhardness: "WSL Calcium Hardness (mg CaCO3/L)",
  wsl_no3no2n: "WSL NO3+NO2 (mg/L)",
  wsl_nh4n: "WSL Ammonia (mg/L)",
  wsl_bromide: "WSL Bromide (mg/L)",
  wsl_chloride: "WSL Chloride (mg/L)",
  wsl_fluoride: "WSL Fluoride (mg/L)",
  wsl_orthophosphate: "WSL Orthophosphate (mg/L)",
  wsl_sulfate: "WSL Sulfate (mg/L)",
  wsl_arsenic: "WSL Aresnic (ug/L)",
  wsl_chromium: "WSL Chromium (ug/L)",
  wsl_copper: "WSL Copper (ug/L)",
  wsl_iron: "WSL Iron (ug/L)",
  wsl_manganese: "WSL Manganese (ug/L)",
  wsl_selenium: "WSL Selenium (ug/L)",
  wsl_uranium: "WSL Uranium (ug/L)",
  wsl_zinc: "WSL Zinc (ug/L)",
  wsl_acetochlor: "WSL Acetochlor (ug/L)",
  wsl_alachlor: "WSL Alachlor (ug/L)",
  wsl_atrazine: "WSL Atrazine (ug/L)",
  wsl_butylate: "WSL Butylate (ug/L)",
  wsl_chlorothalonil: "WSL Chlorothalonil (ug/L)",
  wsl_cyanazine: "WSL Cyanazine (ug/L)",
  wsl_de_ethylatrazine: "WSL De-ethylatrazine (DEA) (ug/L)",
  wsl_de_isopropylatrazine: "WSL De-isopropylatrazine (DIA) (ug/L)",
  wsl_dimethenamid: "WSL Dimethenamid (ug/L)",
  wsl_EPTC: "WSL EPTC (ug/L)",
  wsl_metolachlor: "WSL Metolachlor (ug/L)",
  wsl_metribuzin: "WSL Metribuzin (ug/L)",
  wsl_norflurazon: "WSL Norflurazon (ug/L)",
  wsl_pendamethalin: "WSL Pendamethalin (ug/L)",
  wsl_permethrin: "WSL Permethrin (ug/L)",
  wsl_prometon: "WSL Prometon (ug/L)",
  wsl_proprazine: "WSL Proprazine (ug/L)",
  wsl_propachlor: "WSL Propachlor (ug/L)",
  wsl_simazine: "WSL Simazine (ug/L)",
  wsl_teflurthrin: "WSL Teflurthrin (ug/L)",
  wsl_trifluralin: "WSL Trifluralin (ug/L)",
  wsl_totalcoliform: "WSL Total Coliform (MPN/100 mL)",
  wsl_ecoli: "WSL E. coli (MPN/100 mL)",
  wsl_magnesium: "WSL Magnesium (ug/L)",
  wsl_dateentered: "WSL date entered",
  im_datacollector: "Image Data Collector",
  im_datecollected: "Image Data Date Collected",
  im_filename: "Image Filename",
  im_latitude: "Image Latitude",
  im_longitude: "Image Longitude",
  im_observation: "Image Observation",
  im_type: "Image Type",
  well_id: "Well ID",
  school_id: "School ID",
};

export default csvKey;
