const csvKey = {
    sch_name: "School Name",
    wi_wellcode: "Well Code",
    wi_wellname: "Well Name",
    wi_well_user: "Name of resident well user",
    wi_address: "Address",
    wi_city: "City",
    wi_state: "State",
    wi_zipcode: "Zipcode",
    county_name: "County",
    nrd_name: "Natural Resource District",
    wi_phone_well_user: "Phone # (of well user)",
    wi_email_well_user: "Email (of well user)",
    wi_well_owner: "Well owner (if different from resident)",
    wi_installyear: "Well construction completion year",
    wi_smelltaste: "Complaints of smell or taste",
    wi_smelltaste_description: "Description of smell or taste",
    wi_welldry: "Does the well go dry",
    wi_welldry_description: "Description of well going dry",
    wi_maintenance5yr: "Any maintenance done to well in last 5 years",
    wi_landuse5yr: "Any major land use/development changes around well in last 5 years",
    wi_numberwelluser: "Number of well users",
    wi_pestmanure: "Have manure/fertilizer/pesticides been applied near well in last 5 years",
    wi_estlatitude: "Well Estimated Latitude",
    wi_estlongitude: "Well Estimated Longitude",
    wi_boreholediameter: "Well Bore hole diameter (inches)",
    wi_totaldepth: "Total Depth of Well (feet)",
    wi_waterleveldepth: "Water level (feet)",
    wi_aquifertype: "Aquifer type",
    wi_aquiferclass: "Aquifer class",
    wi_welltype: "Well Type (Construction Method)",
    wi_wellcasematerial: "Well Casing Material",
    wi_dnr_well_id: "DNR Well ID",
    wi_registration_number: "Well Registration Number",
    wi_datacollector: "Well Form Data Collector",
    wi_observation: "Well Observations",
    wi_dateentered: "Well Form Date Entered",
    fa_latitude: "Field Latitude",
    fa_longitude: "Field Longitude",
    fa_weather: "Field Weather Conditions",
    fa_wellcovercondition: "Well Cover Condition",
    fa_wellcoverdescription: "Well Cover Description",
    fa_surfacerunoff: "Evidence of surface run-off at entry of well",
    fa_pooling: "Evidence of pooling or puddles within 12 ft of well",
    fa_groundwatertemp: "Groundwater temp",
    fa_ph: "ph [0-14]",
    fa_conductivity: "Conductivity [100-2000 uS/cm]",
    fa_topography: "Topography of well location",
    fa_datacollector: "Field Form Data Collector",
    fa_observation: "Field Observations",
    fa_datecollected: "Field Date Collected",
    cl_ammonia: "Ammonia [0-10 ppm(mg/L)]",
    cl_calciumhardness: "Calcium Hardness [50-500 ppm(mg/L)]",
    cl_chloride: "Chloride [0-400 ppm(mg/L)]",
    cl_bacteria: "Bacteria (Coilert)",
    cl_copper: "Copper [0-10 ppm(mg/L)]",
    cl_iron: "Iron [0-10 ppm(mg/L)]",
    cl_manganese: "Mangenese [0-50 ppm(mg/L)]",
    cl_nitrate: "Nitrate [0-45 ppm(mg/L)]",
    cl_observation: "Class Lab Observations",
    cl_nitrite: "Nitrate [0-45 ppm(mg/L)]",
    cl_pest_atrazine: "Pesticide/Atrazine (μg/L)",
    cl_datacollector: "Class Lab Data Collector",
    cl_datecollected: "Class Lab Date Entered",
    wsl_samplecode: "Water Science Lab Code",
    wsl_ph: "WSL pH [1-14 (unitless)]",
    wsl_conductivity: "WSL Conductivity (μS/cm)",
    wsl_calciumhardness: "WSL Calcium Hardness (mg CaCO3/L)",
    wsl_no3no2n: "WSL NO3+NO2 (mg/L)",
    wsl_nh4n: "WSL Ammonia (mg/L)",
    wsl_bromide: "WSL Bromide (mg/L)",
    wsl_chloride: "WSL Chloride (mg/L)",
    wsl_fluoride: "WSL Fluoride (mg/L)",
    wsl_orthophosphate: "WSL Orthophosphate (mg/L)",
    wsl_sulfate: "WSL Sulfate (mg/L)",
    wsl_arsenic: "WSL Aresnic (μg/L)",
    wsl_chromium: "WSL Chromium (μg/L)",
    wsl_copper: "WSL Copper (μg/L)",
    wsl_iron: "WSL Iron (μg/L)",
    wsl_manganese: "WSL Manganese (μg/L)",
    wsl_selenium: "WSL Selenium (μg/L)",
    wsl_uranium: "WSL Uranium (μg/L)",
    wsl_zinc: "WSL Zinc (μg/L)",
    wsl_acetochlor: "WSL Acetochlor (μg/L)",
    wsl_alachlor: "WSL Alachlor (μg/L)",
    wsl_atrazine: "WSL Atrazine (μg/L)",
    wsl_butylate: "WSL Butylate (μg/L)",
    wsl_chlorothalonil: "WSL Chlorothalonil (μg/L)",
    wsl_cyanazine: "WSL Cyanazine (μg/L)",
    wsl_de_ethylatrazine: "WSL De-ethylatrazine (DEA) (μg/L)",
    wsl_de_isopropylatrazine: "WSL De-isopropylatrazine (DIA) (μg/L)",
    wsl_dimethenamid: "WSL Dimethenamid (μg/L)",
    wsl_EPTC: "WSL EPTC (μg/L)",
    wsl_metolachlor: "WSL Metolachlor (μg/L)",
    wsl_metribuzin: "WSL Metribuzin (μg/L)",
    wsl_norflurazon: "WSL Norflurazon (μg/L)",
    wsl_pendamethalin: "WSL Pendamethalin (μg/L)",
    wsl_permethrin: "WSL Permethrin (μg/L)",
    wsl_prometon: "WSL Prometon (μg/L)",
    wsl_proprazine: "WSL Proprazine (μg/L)",
    wsl_propachlor: "WSL Propachlor (μg/L)",
    wsl_simazine: "WSL Simazine (μg/L)",
    wsl_teflurthrin: "WSL Teflurthrin (μg/L)",
    wsl_trifluralin: "WSL Trifluralin (μg/L)",
    wsl_totalcoliform: " WSL Total Coliform (MPN/100 mL)",
    wsl_ecoli: "WSL E. coli (MPN/100 mL)",
    wsl_magnesium: "WSL Magnesium (μg/L)",
    wsl_dateentered: "WSL date entered"

}

export default csvKey;