import moment from 'moment';

const devWellInfo = {
    address: "123 Address St",
    aquiferclass: "Bedrock",
    aquifertype: "Confined",
    boreholediameter: "123",
    city: "Kearney",
    county: "9",
    datacollector: "Sample Data Collector",
    dateentered: moment().format('L, h:mm a'),
    dnrId: "5678",
    email: "example@example.com",
    estlatitude: "40",
    estlongitude: "-104",
    installyear: "2020",
    isValidEmail: true,
    isValidPhone: true,
    landuse5yr: "No",
    maintenance5yr: "No",
    numberwelluser: "1",
    nrd: "2",
    observation: "No observations",
    pestmanure: "No",
    phone: "123-456-7890",
    registNum: "ABC1234",
    school_id: "1",
    smelltaste: "Yes",
    smelltastedescription: "Sample smell taste description",
    state: "NE",
    topography: "HillSlope",
    totaldepth: "132",
    wellwaterleveldepth: "21",
    wellcasematerial: "Sample well case material",
    wellcode: "dev123",
    welldry: "Yes",
    welldrydescription: "Sample well dry description",
    wellname: "My Awesome Well (dev)",
    wellowner: "Sample well owner",
    welltype: "Drilled",
    welluser: "Sample well user",
    zipcode: "68502"
};

export default devWellInfo;
