import moment from 'moment';
import { TblWellInfo } from '../../entities/TblWellInfo';

const devWellInfo: TblWellInfo = {
    wiAddress: "123 Address St",
    wiAquiferclass: "Bedrock",
    wiAquifertype: "Confined",
    wiBoreholediameter: 123,
    wiCity: "Kearney",
    countyId: 9,
    wiDatacollector: "Sample Data Collector",
    wiDateentered: moment().toDate(),
    wiDnrWellId: 5678,
    wiEmailWellUser: "example@example.com",
    wiEstlatitude: 40,
    wiEstlongitude: -104,
    wiInstallyear: 2020,
    wiLanduse5yr: "No",
    wiMaintenance5yr: "No",
    wiNumberwelluser: 1,
    nrdId: 2,
    wiObservation: "No observations",
    wiPestmanure: "No",
    wiPhoneWellUser: "123-456-7890",
    wiRegistrationNumber: "ABC1234",
    school: {
        schoolId: 1,
        schName: '',
        schCode: '',
        schAddress: undefined,
        schLatitude: undefined,
        schLongitude: undefined,
        schActiveflag: false,
        schDatedeactivated: undefined,
        schComments: undefined,
        schDateentered: moment().toDate(),
        tblClassrooms: [],
        nrd: undefined,
        tblWellInfos: []
    },
    wiSmelltaste: "Yes",
    wiSmelltasteDescription: "Sample smell taste description",
    wiState: "NE",
    wiTotaldepth: 132,
    wiWaterleveldepth: 21,
    wiWellcasematerial: "Sample well case material",
    wiWellcode: "dev123",
    wiWelldry: "Yes",
    wiWelldryDescription: "Sample well dry description",
    wiWellname: "My Awesome Well (dev)",
    wiWellOwner: "Sample well owner",
    wiWelltype: "Drilled",
    wiWellUser: "Sample well user",
    wiZipcode: "68502",
    wellId: 0,
    wiTopography: undefined,
    wiCommonid: undefined,
    wiComments: undefined,
    tblFieldActivities: undefined,
    tblLandFeatures: undefined,
    tblWellFeatures: undefined,
    tblWellForms: undefined
};

export default devWellInfo;
