const nrdOptions = [
  "Central Platte",
  "Lewis and Clark",
  "Little Blue",
  "Lower Big Blue",
  "Lower Elkhorn",
  "Lower Loup",
  "Lower Niobrara",
  "Lower Platte North",
  "Lower Platte South",
  "Lower Republican",
  "Middle Niobrara",
  "Middle Republican",
  "Nemaha",
  "North Platte",
  "Papio-Missouri River",
  "South Platte",
  "Tri-Basin",
  "Twin Platte",
  "Upper Big Blue",
  "Upper Elkhorn",
  "Upper Loup",
  "Upper Niobrara-White",
  "Upper Republican",
].map((nrd, index) => ({ key: index.toString(), value: nrd }));

export default nrdOptions;
