import moment from 'moment';

const prodWellInfo = {
    address: "",
    aquiferclass: "",
    aquifertype: "",
    boreholediameter: "",
    city: "",
    county: "",
    datacollector: "",
    dateentered: moment().format("llll"), 
    email: "",
    estlatitude: "",
    estlongitude: "",
    installyear: "",
    landuse5yr: "",
    maintenance5yr: "",
    numberwelluser: "",
    nrd: "",
    dnrId: "",
    registNum: "",
    observation: "",
    pestmanure: "",
    phone: "",
    school_id: "",
    smelltaste: "",
    smelltastedescription: "",
    state: "NE",
    totaldepth: "",
    wellwaterleveldepth: "",
    wellcasematerial: "",
    wellcode: "abc123",
    welldry: "",
    welldrydescription: "",
    wellname: "",
    wellowner: "",
    welltype: "",
    welluser: "",
    zipcode: ""
};

export default prodWellInfo;
