import stateOptions from "./states";
import countyOptions from "./counties";
import nrdOptions from "./nrds";

const wellInfoPrompts = [
    {
        type: "shorttextentry",
        fieldTitle: "Well Name:",
        value: "wellname",
        id: "wellname",
        required: true,
    },
    {
        type: "shorttextentry",
        fieldTitle: "Registration Number:",
        value: "registNum",
        id: "registNum",
        required: false,
    },
    {
        type: "numberentry",
        fieldTitle: "DNR Well ID:",
        value: "dnrId",
        id: "dnrId",
        allowDecimal: false,
        required: false,
    },
    {
        type: "shorttextentry",
        fieldTitle: "Name of the resident well user:",
        value: "welluser",
        id: "welluser",
        required: false,
    },
    {
        type: "shorttextentry",
        fieldTitle: "Address:",
        value: "address",
        id: "address",
        required: false,
    },
    {
        type: "shorttextentry",
        fieldTitle: "Village, Town, or City:",
        value: "city",
        id: "city",
        required: false,
    },
    {
        type: "dropdownentry",
        fieldTitle: "State:",
        id: "state",
        options: stateOptions,
        value: "state",
        required: false,
    },
    {
        type: "shorttextentry",
        fieldTitle: "Zipcode:",
        value: "zipcode",
        id: "zipcode",
        required: false,
    },
    {
        type: "dropdownentry",
        fieldTitle: "County:",
        id: "county",
        options: countyOptions,
        value: "county",
        required: true,
    },
    {
        type: "dropdownentry",
        fieldTitle: "NRD:",
        id: "nrd",
        options: nrdOptions,
        value: "nrd",
        required: true,
    },
    {
        type: "shorttextentry",
        fieldTitle: "Well owner (if different from resident):",
        value: "wellowner",
        id: "wellowner",
        required: false,
    },
    {
        type: "shorttextentry",
        fieldTitle: "Phone # (of well user):",
        id: "phone",
        value: "phone",
        errorMessage: "Please use XXX-XXX-XXXX",
        pattern: "^\d{3}-\d{3}-\d{4}$",
        title: "Please enter a valid US phone number in the format XXX-XXX-XXXX.",
    },
    {
        type: "shorttextentry",
        fieldTitle: "Email (of well user):",
        id: "email",
        value: "email",
        errorMessage: "Invalid email address format",
        pattern: "^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$",
        title: "Please enter a valid email address in the format example@example.com",
    },
    {
        type: "numberentry",
        fieldTitle: "Well construction completion year:",
        id: "installyear",
        value: "installyear",
        min: "1800",
        max: "2100",
        required: true,
        allowDecimal: false,
    },
    {
        type: "dropdownentry",
        fieldTitle: "Any complaints about smell or taste of water?",
        id: "smelltaste",
        options: ["Yes", "No", "Unknown"],
        value: "smelltaste",
        required: true,
    },
    {
        dependsOn: "smelltaste",
        conditions: ["Yes"],
        type: "longtextentry",
        fieldTitle: "Description of smell or taste of water:",
        value: "smelltastedescription",
        id: "smelltastedescription",
    },
    {
        type: "dropdownentry",
        fieldTitle: "Does the well ever go dry?",
        id: "welldry",
        options: ["Yes", "No", "Unknown"],
        value: "welldry",
        required: true,
    },
    {
        dependsOn: "welldry",
        conditions: ["Yes"],
        type: "longtextentry",
        fieldTitle: "How often/when does it go dry?",
        value: "welldrydescription",
        id: "welldrydescription",
    },
    {
        type: "dropdownentry",
        fieldTitle: "Any maintenance done to the well itself within the last five years?",
        id: "maintenance5yr",
        options: ["Yes", "No", "Unknown"],
        value: "maintenance5yr",
        required: true,
    },
    {
        type: "dropdownentry",
        fieldTitle: "Any major land use/development changes around the well within the last five years?",
        id: "landuse5yr",
        options: ["Yes", "No", "Unknown"],
        value: "landuse5yr",
        required: true,
    },
    {
        type: "numberentry",
        fieldTitle: "How many people use this well?",
        id: "numberwelluser",
        value: "numberwelluser",
        required: true,
    },
    {
        type: "dropdownentry",
        fieldTitle: "Has any manure, fertilizer, or pesticides been applied near the well within the last five years?",
        id: "pestmanure",
        options: ["Yes", "No", "Unknown"],
        value: "pestmanure",
        required: true,
    },
    {
        type: "numberentry",
        fieldTitle: "Estimated Latitude (in decimal degrees):",
        id: "estlatitude",
        value: "estlatitude",
        min: "40",
        max: "43",
        required: true,
    },
    {
        type: "numberentry",
        fieldTitle: "Estimated Longitude (in decimal degrees):",
        id: "estlongitude",
        value: "estlongitude",
        min: "-104",
        max: "-95.417",
        required: true,
    },
    {
        type: "numberentry",
        fieldTitle: "Bore hole diameter (inches):",
        id: "boreholediameter",
        value: "boreholediameter",
        required: false,
    },
    {
        type: "numberentry",
        fieldTitle: "Total depth of well (feet):",
        id: "totaldepth",
        value: "totaldepth",
        required: false,
    },
    {
        type: "numberentry",
        fieldTitle: "Water level (feet):",
        id: "wellwaterleveldepth",
        value: "wellwaterleveldepth",
        required: false,
    },
    {
        type: "dropdownentry",
        fieldTitle: "Aquifer Type:",
        id: "aquifertype",
        options: ["Confined", "Unconfined", "Unknown"],
        value: "aquifertype",
        required: true,
    },
    {
        type: "dropdownentry",
        fieldTitle: "Aquifer Class:",
        id: "aquiferclass",
        options: ["Bedrock", "Sand or Gravel", "Unknown"],
        value: "aquiferclass",
        required: true,
    },
    {
        type: "dropdownentry",
        fieldTitle: "Well Type (Construction Method):",
        id: "welltype",
        options: ["Drilled", "Driven", "Dug", "Unknown"],
        value: "welltype",
        required: true,
    },
    {
        type: "shorttextentry",
        fieldTitle: "What is the well casing material made of?",
        id: "wellcasematerial",
        value: "wellcasematerial",
        required: false,
    },
    {
        type: "shorttextentry",
        fieldTitle: "Data Collector’s Name:",
        id: "datacollector",
        value: "datacollector",
        required: true,
    },
    {
        type: "longtextentry",
        fieldTitle: "Observations:",
        id: "observation",
        value: "observation",
        required: true,
    },
];

export default wellInfoPrompts;